site_name: Babelsheet

theme: 'material'
docs_dir: docs-src
site_dir: docs

pages:
  - Getting started: index.md
  - Configuration: configuration.md
  - Services: services.md
  - Docker: docker.md
  - How it works: how-it-works.md
  - Development: development.md

extra:
  social:
    - type: 'facebook'
      link: 'https://www.facebook.com/TheSoftwareHousePL/'
    - type: 'twitter'
      link: 'https://twitter.com/realtsh'
    - type: 'circle-o-notch'
      link: 'https://clutch.co/profile/software-house'
